### ISSUE TITLE
Poor performance on all A14 GSIs

### ISSUE THREAD

**Issue by melontini** [TrebleDroid/treble_experimentations#100]
### Current Behavior:
  
Almost all GSIs based on A14 have UI stutters. It feels as if the refresh rate is capped at 5 fps.
  
### To Reproduce
 
1. Boot A14 GSI.
2. Poor performance out of the gate.
3. No visible improvements after ~30 mins.

### Smartphone (please complete the following information):
 - Device: Realme 8 pro
 - Build Flavor: [android_14.0.0_r27 ci-20240208](https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20240208). As well as: [Lineage light](https://sourceforge.net/projects/andyyan-gsi/files/lineage-21-light/lineage-21.0-20240212-UNOFFICIAL-gsi_arm64_gN.img.xz/download), [AOSP by ponces](https://github.com/ponces/treble_aosp/releases/tag/v2024.02.06), [PixelOS](https://github.com/MisterZtr/PixelOS_gsi/releases/tag/v2024.02.18) and [DerpFest](https://github.com/KoysX/treble_DerpFest_GSI/releases/tag/v2024.02.12)
 - Version latest

### Additional context
 
If that helps in any way, the only GSIs which have basically no performance issues are [EvoX](https://github.com/ahnet-69/treble_evo) and, for the most part, [VoltageOS](https://github.com/cawilliamson/treble_voltage/releases/tag/3.2-20240219).

If there's some sort of SurfaceFlinger log, I'd be happy to provide that.

**Comment by phhusson** [comment]
Please try this, as root:
```
setprop debug.sf.enable_gl_backpressure false
pkill -f surfaceflinger
```

**Comment by melontini** [comment]
Thank you for the fast response. This makes EvoX even smoother, but barely has any effect on AOSP by ponces. (Tested using DSU, but I don't think that matters)

**Comment by melontini** [comment]
As a quick and obvious update, I tried the latest TD with the new option in the app, but to no avail.

**Comment by phhusson** [comment]
Could you show the result of `dumpsys SurfaceFlinger` on EvoX and on https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20240222 to see if there is a difference?

**Comment by melontini** [comment]
[evox.txt](https://github.com/TrebleDroid/treble_experimentations/files/14377691/evox.txt) (default backpressure)
[td.txt](https://github.com/TrebleDroid/treble_experimentations/files/14377696/td.txt) (backpressure disabled)

**Comment by phhusson** [comment]
General obversations based on those SF logs:
Both dumps use device compositing
Both use RGBA888_UBWC.
Framebuffer byte size is the same so we can expect compression to be identical
Current color mode is identical both side
Both have colormode srgb, same render intent, same in/out dataspace
EvoX has much more missed frames than TD (though IDK the run time)

Log say " FPS min:61 max:61 cur:61 TransferTime: 0us MaxBrightness:4095" on TD, so I'm not sure where that 30.5 comes from
Both logs have same "vsync on" state to off
Client cache look identical

So yeah except that 30.5FPS thingy, I see nothing wrong in there. If it isn't screen's fps, it could be app rendering which will require systrace.py to check

**Comment by melontini** [comment]
So, the 30 fps things made everything much more confusing. This was the issue, and forcing 61.000004 fixed all the stutters. Thank you very much.

What's strange, is that the treble app doesn't even have a 30 fps option. I wonder why EvoX SurfaceFlinger got it right immediately...
![Screenshot_treble_app_cropped](https://github.com/TrebleDroid/treble_experimentations/assets/104443436/0e45c184-180b-4b26-ba34-a33f2181e83d)

**Comment by melontini** [comment]
I suppose some final observations on the issue:
- Setting the option once fixes the profile forever, even after disabling Force FPS.
- The 30.5 Hz profile is actually used when power save is on.
- Superior OS GSI also correctly detects initial refresh rate.
- Might be a coincidence, but ponces' build with permissive kernel also detected the profile correctly.
