### ISSUE TITLE
Treble app overlays?

### ISSUE THREAD

**Issue by melontini** [TrebleDroid/treble_experimentations#104]
This is more of a question/feature request. Is it possible to create hardware-esque overlays for the Treble App? 

On the realme 8 pro (well, on most phones, I assume), there are some common props which need to be enabled to get calls, VoLTE and headphone jack working (stereo on VoIP, Restart RIL, alt audio policy). While not major, this makes onboarding just a bit easier.

**Comment by phhusson** [comment]
Yes, there is treble_presets for that:
https://github.com/phhusson/treble_presets

I don't think IMS can work that way though, I need to give it a thought.

**Comment by phhusson** [comment]
No, there should be only one, and only during playback. Without
playback there shouldn't be any such process 

 Le mardi 5 mars 2024 à 19:21, melontini ***@***.***> a
écrit :

**Comment by melontini** [comment]
Oh, sorry, constantly during playback.

**Comment by phhusson** [comment]
K. When there is no playback, it consumes 0%?
If you kill it, then let it restart and start playback again, you again see multiple threads consuming 40%?

**Comment by melontini** [comment]
So, after checking again, everything seems to be okay-ish. There are ~12 com.android.bluetooth processes, but only ~7 are active and only 2 consume 30% and 12%. Everything else is <8%. Still seems like a lot, but maybe that's just me.

**Comment by phhusson** [comment]
Just the CPU frequency. It should be 30% of very little

**Comment by melontini** [comment]
Yup the freq is barely affected by the service. Thank you once again.
