### ISSUE TITLE
[Redmi 9] First A14 QPR2 build won't boot (bootloop)

### ISSUE THREAD

**Issue by ghost** [TrebleDroid/treble_experimentations#109]
### Current Behavior:
  
  Device shows OEM logo, then reboots (repeatedly).
### Describe the bug
 
Bootloop
### To Reproduce
 
1. Flash First A14 QPR2 build
2. Wipe data
3. Reboot

### Expected behavior
 
Device can be booted
### Smartphone (please complete the following information):
 - Device: Redmi 9
 - Build Flavor: https://github.com/TrebleDroid/treble_experimentations/releases/download/ci-20240401/system-td-arm64-ab-vanilla.img.xz
 - Version https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20240401

### Additional context
 
Looks like a BPF issue

Logs:
[console-ramoops.txt](https://github.com/TrebleDroid/treble_experimentations/files/14828120/console-ramoops.txt)
[last_kmsg.txt](https://github.com/TrebleDroid/treble_experimentations/files/14828121/last_kmsg.txt)

@phhusson

**Comment by phhusson** [comment]
Could you test with this WIP test image? https://phh.freeboxos.fr:56061/share/KyG5SN_zfL8xcZbx/s-uqpr2-240416-1.img
