### ISSUE TITLE
Question about A-only devices

### ISSUE THREAD

**Issue by smileyhead** [TrebleDroid/treble_experimentations#110]
Hey, I would like to upgrade my Huawei MediaPad M5 Lite to a newer version (it's currently running stock MIUI 8.0.0). My Treble Info results are:

- **Required image:** system-arm64-aonly-img-xz
- **Project Treble:** Supported
- **VNDK version:** 26.0
- **Linker namespace isolation:** VNDK is not in lite mode
- **Manifest location:** Legacy
- **System as Root:** Disabled
- **Seamless Upgrades:** Unsupported
- **Dynamic Partitions:** Unsupported
- **CPU architecture:** ARM64
- **Binder architecture:** 64-bit

This leads me to believe that I would need an A-only GSI to upgrade, but the last release with an A-only image was [AOSP 11.0 v313](https://github.com/phhusson/treble_experimentations/releases/tag/v313). I would assume the latest A/B images in this repo are incompatible. Does this mean release 313 is the final version of Android my tablet is capable of running? 

Thanks in advance.

**Comment by phhusson** [comment]
This is correct. You'll do your own experimentations, but it's possible that the best version for you is rather the even older AOSP 10 v222

**Comment by phhusson** [comment]
FWIW, it might be possible for you to somehow find a way to upgrade to EMUI9, which would give you AB, and would allow you to get Android 14. I think you should be able to find such community upgrades on the internet

**Comment by smileyhead** [comment]
Thank you very much.
