### ISSUE TITLE
GSI build error - cannot find vendor/samsung/hardware/miscpower/2.0/ISehMiscPower.h

### ISSUE THREAD

**Issue by ittat** [TrebleDroid/treble_experimentations#12]
Hi, I get an error when try build GSI: vendor/samsung/hardware/miscpower/2.0/ISehMiscPower.h is not found.
and I can not find the vendor/samsung in the [manifest](https://github.com/TrebleDroid/treble_manifest/tree/android-13.0). can someone tell me what is worry? thanks
https://github.com/TrebleDroid/platform_frameworks_native/commit/9e20d387c8f9b3b43fdd6d837ed9f6155becc614#diff-c244ebb747b47d0d6cd3f67c662f2bc7d34d9c4c8265b09ff6ca1a99b4357a52R23

**Comment by phhusson** [comment]
You're probably missing vendor/interfaces git with pie branch

**Comment by ittat** [comment]
@phhusson Whether to know where was this [generate.sh](https://github.com/phhusson/vendor_interfaces/blob/android-11.0/generate.sh) file executed?

**Comment by phhusson** [comment]
You don't need to execute generate.sh in vendor/interfaces if that's the question
