### ISSUE TITLE
Root access for App

### ISSUE THREAD

**Issue by Ed4Free** [TrebleDroid/treble_experimentations#20]
Hello, 
Thanks for these ROM.
I notice that root is enable for ADB access, "su" works in  "adb shell" 
But for applications no. How to enable root access for application ?
Thierry

**Comment by JonnyTech** [comment]
Install [superuser](https://f-droid.org/en/packages/me.phh.superuser/) app from f-droid ([direct link](https://f-droid.org/repo/me.phh.superuser_1033.apk))

**Comment by Ed4Free** [comment]
Thanks a lot  @JonnyTech, it works fine !

**Comment by Ed4Free** [comment]
And now Debian 10 is working in a Chroot with Linux Deploy :-) 
In it nginx / mysql / php-fpm 
On them Nextcloud, Moodle, Wordpress, Kiwix (wikipedia, etc.)
Thank to you both.
Thierry

**Comment by ED4free** [comment]
> Install [superuser](https://f-droid.org/en/packages/me.phh.superuser/) app from f-droid ([direct link](https://f-droid.org/repo/me.phh.superuser_1033.apk))

Hi @JonnyTech , now I work on Android 14 AOSP ROM, I get the same problem : I get root with ADB but app don't get root.
And this app me.phh.superuser_1033.apk is not compliant with Android 14.
Do you know which Android 14 superuser app I could use to  grant su to app ?
Thank s a lot.

**Comment by ED4free** [comment]
Thanks for your quick answer.
Th problem is that the apk do not install.  It is a problem of min SDK : 
`adb: failed to install me.phh.superuser_1033.apk: Failure [INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 22]`
I use this GSI : android_14.0.0_r27 ci-20240226

**Comment by ED4free** [comment]
I have found the solution : 
adb install --bypass-low-target-sdk-block  .\me.phh.superuser_1033.apk
