### ISSUE TITLE
[Tecno POVA 4 Pro] Vibration does not work

### ISSUE THREAD

**Issue by ddvarpdd** [TrebleDroid/treble_experimentations#21]
### Current Behavior:
Vibration does not work in any GSI-based system at all.
  
### Describe the bug
As I said, nothing that involves vibration works.

### To Reproduce
 
Literally do anything that should normally invoke vibration, like clicking on navigation buttons.

### Expected behavior
 
Vibration working as intended.

### Smartphone (please complete the following information):
 - Device: Tecno POVA 4 Pro (LG8n)
 - Build Flavor: lineage-20.0-20230324-UNOFFICIAL-arm64_bvN.img (lineage-19.1-20230323-UNOFFICIAL-arm64_bvN-vndklite.img to the same results)
 - Version [e.g. V412]

### Additional context
 
Attached are logcats and lshals of both stock ROM (LG8n-H891P-S-RU-221207V1730) and GSI.
[logcat-gsi.txt](https://github.com/TrebleDroid/treble_experimentations/files/11213771/logcat-gsi.txt)
[logcat-stock.txt](https://github.com/TrebleDroid/treble_experimentations/files/11213772/logcat-stock.txt)
[lshal-gsi.txt](https://github.com/TrebleDroid/treble_experimentations/files/11213774/lshal-gsi.txt)
[lshal-stock.txt](https://github.com/TrebleDroid/treble_experimentations/files/11213775/lshal-stock.txt)
Upon further examination, the issue looks similar to https://github.com/phhusson/treble_experimentations/issues/1891. I've poked around in /sys/ and found that vibrator can be activated like this:
```
$ echo 1000 > /sys/class/leds/vibrator_single/duration
$ echo 1 > /sys/class/leds/vibrator_single/activate
```

**Comment by phhusson** [comment]
I would guess vibrator goes through `DM,FC ?
***@***.***::IHap/default
           N/A        N/A`
Please send your ***@***.***
also give the files that appear when doing this command: `grep -r
vendor.transsion.hardware.hyperion.hap /where/is/a/backup/of/stock/system`

**Comment by ddvarpdd** [comment]
Not sure what exact file you need, so here are all files from /vendor named "hyperion": 
[hyperion.tar.gz](https://github.com/TrebleDroid/treble_experimentations/files/11214146/hyperion.tar.gz)

> also give the files that appear when doing this command: `grep -r vendor.transsion.hardware.hyperion.hap /where/is/a/backup/of/stock/system`
```
system/etc/vintf/compatibility_matrix.device.xml:        vendor.transsion.hardware.hyperion.hap_fwk.xml
system/etc/vintf/compatibility_matrix.device.xml:        <name>vendor.transsion.hardware.hyperion.hap</name>
grep: system/framework/hyperion.jar: binary file matches
```

**Comment by ddvarpdd** [comment]
hyperion.jar, if needed (renamed to zip): 
[hyperion.zip](https://github.com/TrebleDroid/treble_experimentations/files/11214158/hyperion.zip)

**Comment by phhusson** [comment]
K, hyperion.hap is not it, it looks related to crypto.
Can you try the same with vendor.transsion.hardware.tne.tneengine instead?

**Comment by ddvarpdd** [comment]
```
grep: system/bin/tne: binary file matches
system/etc/vintf/compatibility_matrix.device.xml:        <name>vendor.transsion.hardware.tne.tneengine</name>
grep: system/framework/services.jar: binary file matches
grep: system/lib/libtnev.so: binary file matches
grep: system/lib/vendor.transsion.hardware.tne.tneengine@1.0.so: binary file matches
grep: system/lib64/libtnev.so: binary file matches
grep: system/lib64/vendor.transsion.hardware.tne.tneengine@1.0.so: binary file matches
```
Attached all the files with hits.
[tne.tar.gz](https://github.com/TrebleDroid/treble_experimentations/files/11215629/tne.tar.gz)

**Comment by ddvarpdd** [comment]
Managed to get it working system-wide, only had to do `chown -R system:system /sys/class/leds/vibrator_single/`. Sorry for wasting your time on the false leads.

**Comment by LordDemecrius83** [comment]
This can be closed now as the vibrator permissions were fixed
