### ISSUE TITLE
No sound during voice calls.

### ISSUE THREAD

**Issue by ivysrono** [TrebleDroid/treble_experimentations#30]
### Current Behavior

When I make voice calls, whether through the top speaker, bottom speaker or Bluetooth headset, I can't hear other people's voices, I've tried many different GSIs and this problem is widespread, My hardwares they are working fine.I also tried many dialers app, the problem is still not solved.
  
### Describe the bug

Things are very simple,Just no sound during voice calls.

### To Reproduce

- Go to the dialer app.
- Dial any number you want.
- When the call is connected,you will see the error.

### Smartphone (please complete the following information)

 - Device: [e.g. [xaga](https://xiaomifirmwareupdater.com/firmware/xaga/) and [chopin](https://xiaomifirmwareupdater.com/firmware/chopin/)]
 
 - Build Flavor: [e.g. any gsi]
 
 - Version [e.g. any version]

**Comment by lemon07r** [comment]
> Redmi Note 11T Pro/Pro+/POCO X4 GT/Redmi K50i Redmi Note 10 Pro 5G/POCO X3 GT

Legion Y70 users also have the same issue on ROMs based on this one. Confirmed on newer versions of the evo x GSI roms, and all the Project Elixir GSI roms after version 3.6.
