### ISSUE TITLE
Are Gapps version not going to release?

### ISSUE THREAD

**Issue by istiak101** [TrebleDroid/treble_experimentations#4]
Hello @phhusson,

Thanks for all the efforts on Treble Droid. Are you no longer going to release Gapps variants?

https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20230120
https://github.com/TrebleDroid/treble_experimentations/commit/4a08a552c53afab19148bfab479414ec70ad2e55

Thanking you again on all of you and other contributors effort on this project. ❤️

**Comment by phhusson** [comment]
The goal of moving this to "TrebleDroid" is so that I'm not the only developer working on it. Other developers are in the TrebleDroid organisation.
I don't want to spend time working on a gapps variant.
But you can try convincing other TrebleDroid developers to do it.

**Comment by ildar** [comment]
Actually there is a TD-based build with GApps: LineageOS 20
<https://forum.xda-developers.com/t/gsi-13-lineageos-20-trebledroid-based.4517345/page-1>

**Comment by istiak101** [comment]
Thanks @phhusson . I understand your situation. I don't want to bother other developers for my personal benefit. Really grateful for all your efforts.

@ildar thank you for pointing me to the right direction. Unfortunately my device(Xiaomi MI A2) is no longer supported by LOS. I will try to pick up patches from all available projects and try to build myself.

**Comment by phhusson** [comment]
You accept asking me, but not other devs?

**Comment by istiak101** [comment]
> You accept asking me, but not other devs?

I only know you from the previous project and currently there are no other public members for this organization. I just wanted to confirm if you want to drop other variant builds. And currently no other ROM developers are working on to support my device and this project was providing only Gapps variants. So, that's why I asked if you wanted to support this anymore.

**Comment by ildar** [comment]
26 янв. 2023 г., 16:24 Istiak Ferdous:

> Unfortunately my device(Xiaomi MI A2) is no longer supported by LOS.
>
This time you are wrong. This LOS is not for a particular device but it
works on every device as Treble Droid.
You should definitely try it

**Comment by istiak101** [comment]
Thank you. I will try treble based one.
