### ISSUE TITLE
android_14.0.0_r14 ci-20231107 Memory Leak And Bluetooth Issue

### ISSUE THREAD

**Issue by nanerbs25** [TrebleDroid/treble_experimentations#64]
So I got the latest Android 14 build(arm32_binder64) then flashed it on my Umidigi A7S (A7S), While Everything is fine, My only problems are reboots when opening large apps such as chrome, then it would reboot, so maybe it has memory leak issue?

Also, Bluetooth doesn't work and sometimes it says "Unfortunately, Bluetooth has stopped".

**Comment by ponces** [comment]
Got logs of both issues?

**Comment by nanerbs25** [comment]
> Got logs of both issues?

actually, my issues on Bluetooth have been fixed, now its just random reboots, i changed gsis bc of that so yeah
