### ISSUE TITLE
A14  Jelly Star (MT6789) not booting

### ISSUE THREAD

**Issue by Mimosatium** [TrebleDroid/treble_experimentations#67]
Hello TrebleDroid Builders,
thanks for your work on our phones.

### Current Behavior:
Stuck at bootanimation.
  
### Describe the bug:
Can't' boot into system.

### To Reproduce:
1. Boot to 'fastbootd'
2. Flash system 'fastboot flash system_a system.img'
3. Wait ... 'flash is successful'
4. Reboot
5. Stuck at bootanimation

### Expected behavior:
System boots.

### Smartphone:
 - Device: Unihertz Jelly Star (Chipset MT6789 Helio G99, A12 native vendor, stock kernel 5.10)
 - Build Flavor:  system-td-arm64-ab-vanilla.img.xz
 - Version android_14.0.0_r14 ci-20231117 (and previous ones)

### Logcat:
[logcat_Jelly_Star_AOSP_A14.txt](https://github.com/TrebleDroid/treble_experimentations/files/13419573/logcat_Jelly_Star_AOSP_A14.txt)

### Additional context:
android_13.0.0_r73 ci-20230830 doesn't boot then android_13.0.0_r73 ci-20230905 boots.
Google's official A14 UPB2.230407.014.A1 boots, but after that no others A14 releases work (AOSP Google/TD/ponces, Derpfest, PixelOS, ...).

Let me know if anything more is needed, if you choose to help me (I understand that my phone is a bit exotic).

**Comment by ponces** [comment]
Can you please do a factory reset with your device's stock recovery and try again?

**Comment by Mimosatium** [comment]
Thank you for your reply.
I tried your advice and did a factory reset with stock recovery but unfortunately it's worse.
Now after flashing TD AOSP 14.0.0_r14 ci-20231123 or your AOSP 14.0 v2023.11.24 from stock fastbootd (no custom recovery for my device), it shows OEM logo, shows black screen, shows OEM logo and then shows a kind of lite recovery without no option just "Try again".
After selecting "Try again", it shows OEM logo, shows black screen, shows OEM logo and then shows a kind of lite recovery without no option just "Try again"....
So I can't even provide you log.

**Comment by ponces** [comment]
No pstore log?

**Comment by phhusson** [comment]
I think this way of making logs work. There is a lot of noise about magisk, but I think we can survive it. Can you try to edit the AOSP 14 GSI you flash, to edit system/bin/rw-system.sh and remove its `dmesg -n 1` line? It's eating logs

**Comment by Mimosatium** [comment]
Thank you for you feedback Mr phhusson.
I never ever edited a system.img, so I don't know how to make it.
I tried to modify your [securize.sh](https://github.com/phhusson/sas-creator/blob/master/securize.sh) (remove all cmd lines 32 to 37 and add `nano system/bin/rw-system.sh`) to remove `dmesg -n 1` line.
I installed it using DSU and rebooted but my device bootloops (OEM logo, black screen then reboot to Lineage system).
Anyway I pulled pstore log when Lineage booted.
Log finishes by `dm-verity device corrupted` so I think my method wasn't the good one. Have you some advises ?

[console-ramoops-0.txt](https://github.com/TrebleDroid/treble_experimentations/files/13493643/console-ramoops-0.txt)

**Comment by phhusson** [comment]
Well it's perfectly your boot.img (from stock rom patched with magisk) doesn't allow booting GSIs in DSU... When flashing lineageos, did you flash vbmeta as well with `fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img` ?

**Comment by Mimosatium** [comment]
No I didn't flash vbmeta cause if I flashed it device always bootloops.
I followed [this](https://www.reddit.com/r/UnihertzJelly2/comments/15z1xdz/jelly_star_rooted/) and [this](https://www.reddit.com/r/unihertz/comments/16sviga/unihertz_jelly_star_running_great_with_lineageos/).

**Comment by Mimosatium** [comment]
I come back with my problem because I am not really understand latest phhusson's message. My device allows booting GSIs in DSU, it can boot TD's android_13.0.0_r73 ci-20230905 or AndyCGYan's lineage-20.0-20231214-UNOFFICIAL-arm64_bvN for example.
I think my lack of experience in editing the system.img file caused the `dm-verity device corrupted` line in log, last time.
So I try again with latest TD's release ci-20231208 android_14.0.0_r17. It bootloops like previous one (stuck at bootanimation).
I uninstalled Magisk (to avoid the noise in logs), tried to remove `dmesg -n 1` line in `/system/bin/rw-system.sh` (but I couldn't find them in this release) and catched logs. I really hope you'll can help me.

[logcat.txt](https://github.com/TrebleDroid/treble_experimentations/files/13693639/logcat.txt)
[console-ramoops-0.txt](https://github.com/TrebleDroid/treble_experimentations/files/13693643/console-ramoops-0.txt)

**Comment by ponces** [comment]
> No I didn't flash vbmeta cause if I flashed it device always bootloops with any GSI A13/A14 I tested. Only two LineageOS 20 releases (august and november) and one TD's AOSP 13 (20230905) work without flashing vbmeta. I followed [this](https://www.reddit.com/r/UnihertzJelly2/comments/15z1xdz/jelly_star_rooted/) and [this](https://www.reddit.com/r/unihertz/comments/16sviga/unihertz_jelly_star_running_great_with_lineageos/). It says ` With the Jelly 2 we had to include verity/verification commands. Don't do that here since it'll result in a bootloop.`. Hope my device isn't `GSI non grata`.

Can you retry this process but this time with these three following commands:
```
fastboot flash --disable-verification --disable-verity vbmeta vbmeta.img
fastboot flash --disable-verification --disable-verity vbmeta_system vbmeta.img
fastboot flash --disable-verification --disable-verity vbmeta_vendor vbmeta.img
```

**Comment by Mimosatium** [comment]
I didn't have much time the evening so I quickly tried your commands : 
`fastboot flash --disable-verification --disable-verity vbmeta vbmeta.img`
`fastboot flash --disable-verification --disable-verity vbmeta_system_a vbmeta.img`
`fastboot flash --disable-verification --disable-verity vbmeta_vendor_a vbmeta.img`
and tried to reboot the installed system (lineage-20.0-20231214-UNOFFICIAL-arm64_bvN). It didn't work, my phone bootlooped (it showed OEM logo, showed black screen, showed OEM logo and then showed a kind of lite recovery without no option just "Try again") so I flashed stocks vbmetas and catched log at reboot.
[console-ramoops-0.txt](https://github.com/TrebleDroid/treble_experimentations/files/13732823/console-ramoops-0.txt)

I also tried :
`fastboot flash --disable-verification --disable-verity vbmeta_a vbmeta.img`
`fastboot flash --disable-verification --disable-verity vbmeta_system_a vbmeta_system.img`
`fastboot flash --disable-verification --disable-verity vbmeta_vendor_a vbmeta_vendor.img`
`fastboot flash --disable-verification --disable-verity vbmeta_b vbmeta.img`
`fastboot flash --disable-verification --disable-verity vbmeta_system_b vbmeta_system.img`
`fastboot flash --disable-verification --disable-verity vbmeta_vendor_b vbmeta_vendor.img`
same result.
[console-ramoops-0_.txt](https://github.com/TrebleDroid/treble_experimentations/files/13732844/console-ramoops-0_.txt)

I will try the complet process with your commands, from a clean stock installation, in next days when I will have much time, thanks for your attention.

**Comment by phhusson** [comment]
Both those logs say "[   31.710134][T200268] init: Received sys.powerctl='reboot,userrequested,recovery' from pid: 283 (/system/bin/recovery)" which says that you requested to reboot to recovery.
I don't quite get what could happen that Android decides you want to reboot in recovery within 30s...
You only get console-ramoops in logs, no pmem?

**Comment by phhusson** [comment]
https://github.com/TrebleDroid/treble_experimentations/issues/67#issuecomment-1858909887 This log says something else, that's a bug on our side.
Can you test https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20231025 ?

**Comment by Mimosatium** [comment]
I didn't request to reboot to recovery. I used : `fastboot reboot`
The phone tried to reboot normally (OEM logo) then there was a black screen, OEM logo again and it booted to a kind of recovery without any option, just "Try again". There was no other choice so I selected "Try again". It rebooted and so on indefinitely.

I don't understand log but I saw the last line `reboot: Restarting system with command 'userrequested,recovery'`. I suspected that this would not be good for your understanding of the problem. I would have like to catch log without this reboot to recovery.
So I restarted the process from the begining and just after the first black screen, I booted to SP Flash Tool mode (don't know the name of this mode) to flash stocks vbmetas (successfully), but after that it rebooted anyway to the lite recovery with only "Try again". Only after that, it rebooted to system normally.

I will try again from stock installation with "fastboot flash --disable-verification --disable-verity vbmeta_a vbmeta.img ..." and android_14.0.0_r2 ci-20231025 as soon as possible.
There is also a pmsg-ramoops-0 file in /sys/fs/pstore/, I will give it to you next time.
Merci à vous deux de vous intéressez à mon problème et désolé pour mon anglais.

**Comment by Mimosatium** [comment]
So, I reinstalled stock rom and then `"fastboot flash --disable-verification --disable-verity vbmeta_a vbmeta.img ...` and flashed android_14.0.0_r2 ci-20231025.
Result : my phone bootlooped before bootanimation.

I took advantage of the situation to try another thing that I had investigated. Because it seems my phone dislikes verification/verity disabling. I created new vbmeta/vbmeta_system almost similar to stock ones just I used system-td-arm64-ab-vanilla.img for the system :
> python ./avbtool.py make_vbmeta_image \
>     --key rsa2048_vbmeta.pem \
>     --algorithm SHA256_RSA2048 \
>     --flag 0 \
>     --chain_partition boot:1:keys/boot_key.bin \
>     --chain_partition vbmeta_system:3:keys/rsa2048_vbmeta.bin \
>     --chain_partition vbmeta_vendor:4:keys/vbmeta_vendor_key.bin \
>     --include_descriptors_from_image ./dtbo.img \
>     --include_descriptors_from_image ./vendor_boot.img \
>     --include_descriptors_from_image ./odm_dlkm_a.img \
>     --include_descriptors_from_image ./vendor_dlkm_a.img \
>     --padding_size 4096 \
>     --output vbmeta-custom.img
> 
> python ./avbtool.py make_vbmeta_image \
>     --key rsa2048_vbmeta.pem \
>     --algorithm SHA256_RSA2048 \
>     --flag 0 \
>     --include_descriptors_from_image ./product_a.img \
>     --include_descriptors_from_image ./system-td-arm64-ab-vanilla.img \
>     --padding_size 4096 \
>     --output  #vbmeta_system-custom.img

Then :
> fastboot flash vbmeta_a vbmeta-custom.img
> fastboot flash vbmeta_system_a vbmeta_system-custom.img
And like that, the phone boots to A14.

I tried same thing with android_14.0.0_r2 ci-20231025 and android_14.0.0_r17 ci-20231220 system.img, it worked.
I also tried with ponces's AOSP 14.0 v2023.12.17 one but it didn't work.
So it's not perfect but it's a good begining and it responds to my issue.

You can close the issue except if you want to investigate on :
> [#67 (comment)](https://github.com/TrebleDroid/treble_experimentations/issues/67#issuecomment-1858909887) This log says something else, that's a bug on our side.
or if you have any advise to improve the process.
If necessary I can catch logs more easily now.

Anyway, thank you for your help ponces and phhusson, and thank you for all your work for GSI's world.

**Comment by ponces** [comment]
Well... I didn't knew about that possibility of creating our own vbmeta images. Thanks for the info!
What happens if you try to boot my AOSP with one vbmeta generated from TD system image?

**Comment by Mimosatium** [comment]
> What happens if you try to boot my AOSP with one vbmeta generated from TD system image?

I tried to boot your release using vbmeta_system generated with TD system image (and also tried again with your system image), unfortunately in both cases my phone bootlooped (OEM logo, black screen, reboot) as with stock vbmeta_system.
I also tried this process with Nazim's crDroid 14 and chrisaw's VoltageOS 14, it bootlooped too. I saw that all these realeases are signed with release-keys, maybe it explains this problem.
TD's AOSP 14 and AndyYan's LineageOS TD-based 13 (and also 14 pre-release) which are signed with test-keys boot perfectly.

**Comment by DocMAX** [comment]
Just want to say i have a Jelly Star with exactly the same problems.
Just some recent LOS 20 GSI from Andy Yan work, nothing else.

fastboot flash --disable-verification --disable-verity vbmeta_x vbmeta.img
Does break everything. No GSI works.

**Comment by DocMAX** [comment]
> > --chain_partition vbmeta_system:2:keys/rsa2048_vbmeta.bin 
where did you get rsa2048_vbmeta.bin? or is it rsa2048_vbmeta.PEM?

**Comment by Mimosatium** [comment]
> > --chain_partition vbmeta_system:2:keys/rsa2048_vbmeta.bin
> 
> where did you get rsa2048_vbmeta.bin? or is it rsa2048_vbmeta.PEM?
> 
> @Mimosatium or can you just provide all files necessary?
> 
> lineage-20.0-20240217-UNOFFICIAL-arm64_bgN.img peter_gsi_arm64_20230822.img gargoyle_bgN.img
> 
> These are the only ROMs that work on my Jelly Star stock vbmeta. Seems to work only with A13. WHY IS THAT? What makes them different?

Commands are inspired from [this](https://www.hovatek.com/forum/thread-32664.html). Your question corresponds to step 4, you need to generate a public key from the private key, so :
`python3 ./avbtool extract_public_key --key rsa2048_vbmeta.pem --output keys/rsa2048_vbmeta.bin`
boot_key.bin and vbmeta_vendor_key.bin come from boot.img, follow [this](https://www.hovatek.com/forum/thread-32667.html).
All others .img (except system.img) come from stock ROM zip file and from [unpacking](https://github.com/VeloshGSIs/Super_Guide) stock super.img.

The process works to boot [TD's AOSP 14](https://github.com/TrebleDroid/treble_experimentations/releases).
For [AndyYan's LineageOS 21 TD-based](https://sourceforge.net/projects/andyyan-gsi/files/lineage-21-td//), you need to modify the system.img name in :
`--include_descriptors_from_image system-td-arm64-ab-vanilla.img`

**Comment by DocMAX** [comment]
How can boot_key.bin and vbmeta_vendor_key.bin come from boot.img? Do i have to unpack boot.img? Are you somewhere around to talk? Discord, IRC,...?

**Comment by Mimosatium** [comment]
> How can boot_key.bin and vbmeta_vendor_key.bin come from boot.img? Do i have to unpack boot.img? Are you somewhere around to talk? Discord, IRC,...? Also boot.img is not mentioned in the guides.

Sorry, my mistake, it comes from vbmeta.img.

**Comment by DocMAX** [comment]
Yeah, i picked them with hex editor. Here are mine, can you share yours? (from 2023112915_g58v89c2k_dfl_eea)
[keys.zip](https://github.com/TrebleDroid/treble_experimentations/files/14438991/keys.zip)

**Comment by Mimosatium** [comment]
> Yeah, i picked them with hex editor. Here are mine, can you share yours? (from 2023112915_g58v89c2k_dfl_eea) [keys.zip](https://github.com/TrebleDroid/treble_experimentations/files/14438991/keys.zip) I probably extracted them wrong. I have all files in place, building the custom vbmeta but still get a bootloop on AndyYans Lineage 21.

Your vbmeta_vendor_key.bin seems to be wrong.
Here mine [keys.zip](https://github.com/TrebleDroid/treble_experimentations/files/14439029/keys.zip)

**Comment by DocMAX** [comment]
Bootloop... I probably will never make this work.
Does it really work with lineage-20.0-20240217-UNOFFICIAL-arm64_bgN.img?

Can we compare our folders?
```
docmax@gpdwinmax2: /mnt/pve/data/software/android/devices/jellystar/vbmeta_custom $ LANG= ls -la -R
.:
total 2542704
drwxr-xr-x 3 docmax docmax         16 Feb 28 20:30 ./
drwxr-xr-x 7 docmax docmax          7 Feb 28 11:36 ../
-rwxr--r-- 1 docmax docmax    8388608 Nov 29 08:37 dtbo.img*
drwxr-xr-x 2 docmax docmax          6 Feb 28 20:24 keys/
lrwxrwxrwx 1 docmax docmax         89 Feb 28 20:29 lineage-21.0-20240217-UNOFFICIAL-arm64_bgN.img -> /mnt/pve/data/software/android/devices/gsi/lineage-21.0-20240217-UNOFFICIAL-arm64_bgN.img
-rw-r--r-- 1 docmax docmax     348160 Feb 28 01:57 odm_dlkm_a.img
-rw-r--r-- 1 docmax docmax 2541166592 Feb 28 02:12 product_a.img
-rw-r--r-- 1 docmax docmax       1700 Jul 24  2020 rsa2048_vbmeta.pem
-rw-r--r-- 1 docmax docmax       8192 Feb 28 20:30 vbmeta-custom.img
-rwxr-xr-x 1 docmax docmax       1039 Feb 28 20:30 vbmeta_custom.sh*
-rw-r--r-- 1 docmax docmax       4096 Feb 28 19:55 vbmeta_disabled.img
-rw-r--r-- 1 docmax docmax       4096 Feb 28 20:30 vbmeta_system-custom.img
-rwxr--r-- 1 docmax docmax       4096 Nov 29 08:37 vbmeta_system.img*
-rwxr--r-- 1 docmax docmax       4096 Nov 29 08:37 vbmeta_vendor.img*
-rw-r--r-- 1 docmax docmax   67108864 Feb 28 01:41 vendor_boot.img
-rw-r--r-- 1 docmax docmax   33689600 Feb 28 01:56 vendor_dlkm_a.img

./keys:
total 35
drwxr-xr-x 2 docmax docmax   6 Feb 28 20:24 ./
drwxr-xr-x 3 docmax docmax  16 Feb 28 20:30 ../
-rwxr--r-- 1 docmax docmax 520 Feb 28 11:14 boot_key.bin*
-rw-r--r-- 1 docmax docmax 520 Feb 28 17:05 rsa2048_vbmeta.bin
-rwxrwxrwx 1 docmax docmax 520 Dec 16 10:44 vbmeta_system_key.bin*
-rwxrwxrwx 1 docmax docmax 520 Dec 16 10:44 vbmeta_vendor_key.bin*

```

**Comment by Mimosatium** [comment]
I use lineage-21.0-20240217-UNOFFICIAL-arm64_bvN.img, I don't know if it works with googled one.

```
~/Smartphone/Jelly_Star/avtool$ ls -la -R
.:
total 2588852
drwxrwxrwx 1 root root      12288 28 févr. 20:45 .
drwxrwxrwx 1 root root      24576 28 févr. 20:43 ..
-rwxrwxrwx 1 root root     206330 10 juil.  2023 avbtool.py
-rwxrwxrwx 1 root root    8388608 29 nov.  15:37 dtbo.img
drwxrwxrwx 1 root root       4096 28 févr. 20:23 keys
-rwxrwxrwx 1 root root     348160  9 déc.  00:17 odm_dlkm_a.img
-rwxrwxrwx 1 root root 2541166592  9 déc.  00:17 product_a.img
-rwxrwxrwx 1 root root       1700 24 juil.  2020 rsa2048_vbmeta.pem
-rwxrwxrwx 1 root root       8192 29 nov.  15:37 vbmeta.img
-rwxrwxrwx 1 root root       8192 11 févr. 19:25 vbmeta-los21.img
-rwxrwxrwx 1 root root       4096 29 nov.  15:37 vbmeta_system.img
-rwxrwxrwx 1 root root       4096 11 févr. 19:26 vbmeta_system-los21.img
-rwxrwxrwx 1 root root       4096 29 nov.  15:37 vbmeta_vendor.img
-rwxrwxrwx 1 root root   67108864 29 nov.  15:37 vendor_boot.img
-rwxrwxrwx 1 root root   33689600  9 déc.  00:17 vendor_dlkm_a.img

./keys:
total 20
drwxrwxrwx 1 root root  4096 28 févr. 20:23 .
drwxrwxrwx 1 root root 12288 28 févr. 20:45 ..
-rwxrwxrwx 1 root root   520 16 déc.  10:43 boot_key.bin
-rwxrwxrwx 1 root root   520 16 déc.  12:08 rsa2048_vbmeta.bin
-rwxrwxrwx 1 root root   520 16 déc.  10:44 vbmeta_system_key.bin
-rwxrwxrwx 1 root root   520 16 déc.  10:44 vbmeta_vendor_key.bin
```

My [vbmeta.zip](https://github.com/TrebleDroid/treble_experimentations/files/14439304/vbmeta.zip) generate from 2023112915_g58v89c2k_dfl_eea.zip and lineage-21.0-20240201-UNOFFICIAL-arm64_bvN.img (I updated to 20240217 after without changing vbmetas).

I need many try to make it works and sometimes, even with good vbmetas it didn't boot so I needed to reflash stock ROM from the begining.
Using first stock ROM release (2023072513_g58v89c2k_dfl_eea.zip) can help in some case, cause there is a "Factory reset" option in bootloop recovery.

**Comment by DocMAX** [comment]
Got it working after many tries like you. This phone is really a pain in the ***.
One annoying thing it has like the A13 ROMS is there is no haptic feedback with the hardware touch buttons.
@phhusson Do you have a hint what can be done about it? I was hoping to find something in "Phh Treble Settings".

**Comment by Mimosatium** [comment]
Happy for you. It works with googled release ?
KernelSU works well for me. Unpack stock boot.img using magiskboot, then delete `kernel` file, unzip `Image` one in AnyKernel3-android12-5.10.198_2023-11.zip, rename it `kernel` and repack with magiskboot.
With KernelSU, you can make rear light works with [this](https://gitea.angry.im/PeterCxy/Lunatic/releases/tag/202304291132) (after resigning apk with `testkey.x509.pem` and give it root privileges).

**Comment by DocMAX** [comment]
Yes googled release works. Great you also know about KernelSU. Does haptic feedback work with the kernel?
Somehow my vbmeta-custom.img doesn't look like yours and i can't get it excatly like yours. I don't know what i am doing wrong.
Also using 2023112915_g58v89c2k_dfl_eea.zip and lineage-21.0-20240201-UNOFFICIAL-arm64_bvN.img to generate it.
Here is mine. [vbmeta-custom.zip](https://github.com/TrebleDroid/treble_experimentations/files/14440371/vbmeta-custom.zip)

**Comment by Mimosatium** [comment]
Sorry, I'm not interested in haptic feedback. I just tried to activate it but nothing.
It's weird with your vbmeta.img, it's like if you used boot.img instead of vendor_boot.img to generate it ???? Try to read vendor _boot.img with `python3 ./avbtool.py info_image --image vendor _boot.img` to see if it's the good file. 
```
Footer version:           1.0
Image size:               67108864 bytes
Original image size:      22659072 bytes
VBMeta offset:            22659072
VBMeta size:              640 bytes
--
Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     0 bytes
Auxiliary Block:          384 bytes
Algorithm:                NONE
Rollback Index:           0
Flags:                    0
Rollback Index Location:  0
Release String:           'avbtool 1.2.0'
Descriptors:
    Hash descriptor:
      Image Size:            22659072 bytes
      Hash Algorithm:        sha256
      Partition Name:        vendor_boot
      Salt:                  560d1b418a869614d78f295eba905b4d356349ae25d8a725481df1fe5143adc3
      Digest:                56092994017b6f1eefa4a565c75c14bf8818312a9760fa78ec4f51bee166b7ca
      Flags:                 0
    Prop: com.android.build.vendor_boot.fingerprint -> 'Unihertz/Jelly_Star_EEA/Jelly_Star:12/SP1A.210812.016/root.20230627.201104:user/release-keys'
```
Maybe try to delete your vendor_boot.img and unzip them again from stock ROM zip ????

> Also warning message doesn't appear with this vbmeta

The `Orange state` message at boot ?

**Comment by DocMAX** [comment]
Sorry, i deleted my message as i realized that i can not just sign with a patched vendor_boot.img. I replaced vendor_boot.img with magisk patched boot.img and KernelSU .img. This completly doesn't work :-)

**Comment by DocMAX** [comment]
Needing assitance with KernelSU. I unpacked stock boot.img with aik-unpack, replaced 
boot.img-kernel                               │ 19088K
with
Image                                         │ 36655K from AnyKernel
aik-repack
flashed image-new.img to boot_a
bootloop :-(

**Comment by DocMAX** [comment]
No other GSI works so far with this vbmeta signing method... :-( wtf?

**Comment by Mimosatium** [comment]
The process is good but use magiskboot (unzip latest magisk-vXX.X.apk, find /lib/x86_64/libmagiskboot.so, rename it magiskboot) instead of aik-unpack.
You need to obtain a KernelSU-boot.img with the same "avb signature" as stock-boot.img. magiskboot makes it, I think that aik-unpack not.
Compare using : `python3 ./avbtool.py info_image --image boot.img`
Don't know if it works but you can also test : `python3 ./avbtool.py append_vbmeta_image --image your_boot_kernelsu_from_aik-unpack.img --partition_size 67108864 --vbmeta_image stock-boot.img`

About GSI with test-keys signature, it's just a (wrong) supposition.
Use : `python3 ./avbtool.py info_image --image system.img` and watch `Prop: com.android.build.system.fingerprint` to check how they are signed.
I tested many GSI, the only ones that work (LineageOS, TD's AOSP, LeOS-20) use testkeys. PeteCai's GSI is the only ones using release-keys that work. ????
So I don't know why Jelly Star isn't GSI friendly.

**Comment by DocMAX** [comment]
All right, thank you. Just for fun this is my current testing list:
```
AfterLife_A13-RO-arm64-bgN-slim_20240119.img
AncientOS-T-Shield-v7.3-a64_bgN-Steel-20231001.img
aosp-arm64-ab-gapps-14.0-20240227.img
ArrowOS-13.1-a64_bgN-Unofficial.img
Bliss-2019-04-04-arm64-ab-gapps.img
ColtOS_A13-RO-arm64-bgN-slim_20240124.img
crDroid-10.1-arm64_bgN-Unofficial.img
DerpFest-arm64_bgN-14.0-unofficial-20240108.img
evolution_arm64_bgN-8.3-unofficial-20240207.img
gargoyle_bgN.img
gargoyle_slim_bgN.img
IMG-e-1.17-q-20231110351091-dev-treble_arm64_bvN.img
LeOS-20-VNDK-arm64_bvN.img
lineage-16.0-20191017-UNOFFICIAL-treble_arm64_bvN.img
lineage-17.1-20210808-UNOFFICIAL-treble_arm64_bvS.img
lineage-18.1-20240121-UNOFFICIAL-arm64_bgS.img
lineage-19.1-20240120-UNOFFICIAL-arm64_bgN.img
lineage-20.0-20240215-UNOFFICIAL-gsi_arm64_gN.img
lineage-20.0-20240217-UNOFFICIAL-arm64_bgN.img
lineage-21.0-20240201-UNOFFICIAL-arm64_bvN.img
lineage-21.0-20240212-UNOFFICIAL-gsi_arm64_gN.img
lineage-21.0-20240217-UNOFFICIAL-arm64_bgN.img
lineage-21.0-20240217-UNOFFICIAL-arm64_bvN.img
MikuUI-Udon-0.4.0-arm64-ab-gapps-20231214-UNOFFICIAL.img
NothingOS-2.0-AB-13-20230713-NipponGSI.img
peter_gsi_arm64_20230822.img
peter_gsi_arm64_android14_20231111.img
PixelExperience_Plus_arm64-ab-13.0-20230914-UNOFFICIAL.img
PixelOS_treble_arm64_bN-14.0-20240218.img
ProjectElixir_3.13_arm64_bgN-13.0-20231105-0917-OFFICIAL.img
ProjectElixir_4.1_arm64_bgN-14.0-20240226-1114-OFFICIAL.img
SparkOS-13.8-arm64_bgN-Unofficial.img
SuperiorOS_A14-arm64-bgS-slim_20242024.img
SuperiorOS_A14-arm64-bgS-slim-vndklite_20242024.img
SuperiorOS_A14-arm64-bvS_20242024.img
SuperiorOS_A14-arm64-bvS-vndklite_20242024.img
SuperiorOS_A14-RO-arm64-bgN-slim_20242024.img
system-td-arm64-ab-vanilla_01.img
system-td-arm64-ab-vanilla.img
VoltageOS-arm64-ab-3.2-20240226-UNOFFICIAL.img
```
I can confirm only works what you mentioned. I hope some greater expert can help us someday.

**Comment by DocMAX** [comment]
Found this script that makes all the work. Works for me too. aik-repack was the issue.

**Comment by DocMAX** [comment]
OK, Peter's ROMs are the way to go. After looking into it's sources at https://gitea.angry.im/PeterGSI/android_device_peter_gsi he added some unique quirks for Jelly Star.

**Comment by Mimosatium** [comment]
> @Mimosatium One more question, did you test the "light" variant (lineage-21.0-20240212-UNOFFICIAL-gsi_arm64_gN.img)? Does it boot? I replace it with my current TD -> bootloop. But i also don't want to delete my data right now. Thanks.

I tested it with stock vbmeta/vbmeta_system.img, it didn't boot. But maybe with custom vbmetas ???
Before, I used custom vbmetas, I tested GSI with [DSU-Sideloader](https://github.com/VegaBobo/DSU-Sideloader), so that I didn't have to erase my data. Now I just use it to test new LOS21 releases before flashing it.

> Found this script that makes all the work. Works for me too. aik-repack was the issue.

What script ? I'm interested.

**Comment by DocMAX** [comment]
Sorry, didn't include link... https://gist.github.com/skrimix/cc351cff8c01596ef6babafd0339c854

**Comment by Do-Do666** [comment]
Does the lamp band function work normally?

**Comment by Do-Do666** [comment]
> what is a lamp band function?
LED lamp
![IMG_20240617_114341.jpg](https://github.com/TrebleDroid/treble_experimentations/assets/161176501/98d1f217-429d-404f-99bc-dc81407335f0)

![IMG_20240617_114350.jpg](https://github.com/TrebleDroid/treble_experimentations/assets/161176501/baf40781-7161-4da5-b897-bdbadac30eeb)
