### ISSUE TITLE
Secure images bootloop MTK devices

### ISSUE THREAD

**Issue by JonnyVR1** [TrebleDroid/treble_experimentations#7]
### Current Behavior:
Building a secure image results in bootloops on MTK devices
  
### Describe the bug
https://github.com/TrebleDroid/device_phh_treble/blob/812b0e8bff7f4f40ca3c168c7c220c290f7842fa/rw-system.sh#L768

It's something about one (or more) of the props reset in lines 768-781 of rw-system.sh in the device tree - I haven't yet had enough time to narrow down the exact prop or props that causes the issue

### To Reproduce
Build a secure image (or run the phh-securize.sh script if an image is already on the device)
Observe bootloops

### Expected behavior
Secure builds do not bootloop

### Smartphone (please complete the following information):
 - Device: Umidigi A13 Pro Max 5G
 - Build Flavor: system-td-arm64-ab-secure.img.xz - built from source as secure image is only provided here for vndklite devices.
 - Version: Code up-to-date with the [android_13.0.0_r24 ci-20230120](https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20230120) build

**Comment by JonnyVR1** [comment]
resetprop_phh ro.boot.flash.locked 1

**Comment by phhusson** [comment]
Please grab logs (you'll need to remove the sections related to adb in rw-system.sh's secure path to keep working adb in secure mode)
What is the Android version of the vendor?

The proper fix will probably be to add those properties here:

https://github.com/TrebleDroid/platform_bionic/commit/530cd7391634cd547681c99d970c3ad37f0c779f#diff-df07ad10baba3f483d36a4fd9c25bf6129906f5a0095cdab7e92eee34ac74858R103
 and redirect them to report orange/unlocked rather than the real value

**Comment by JonnyVR1** [comment]
Vendor is Android 12. I've tried getting logs before but it doesn't get far enough in the boot cycle for ADB to initialise.

**Comment by phhusson** [comment]
So I'm trying the thing I mentioned before about faking the properties in bionic. For that, I need you to give the following infos (on whichever ROM/GSI):
- Does /proc/tkcore/tkcore_log exist?
- Does /vendor/bin/hw/android.hardware.keymaster@4.1-service.trustkernel exist?
- Give the result of `ps -A |grep -e tee -e keymaster` run from adb shell

**Comment by JonnyVR1** [comment]
/proc/tkcore/tkcore_log exists
/vendor/bin/hw/[ndroid.hardware.keymaster@4.1-service.trustkernel exists

A13_Pro_Max_5G:/ # ps -A |grep -e tee -e keymaster
root           135     2       0      0 logd                0 S [tee-log]
system         927     1 10839128  2552 down_interruptible  0 S teed
system         933     1 10800248 15852 binder_ioctl_write_read 0 S android.hardware.keymaster@4.1-service.trustkernel

**Comment by phhusson** [comment]
ok all good. well actually I'm guessing I'll have the say issue on my cubot pocket 3, i'll try. ( I didn't hit it previously because i never securize)

**Comment by JonnyVR1** [comment]
phh-su and Magisk don't play nicely together and I've had multiple issues if both were present - securizing removes phh-su but introduces the bootloops, that's why I'm making a big issue about this, for me a working Magisk is kinda non-negotiable so it's a pretty big deal.

I'm happy to test any experiments needed.

**Comment by phhusson** [comment]
I'm pretty confident that a pure magisk setup without safetynet bypass doesn't lead to that issue.

**Comment by phhusson** [comment]
Reproduced on Cubot Pocket 3. Fixed with https://github.com/TrebleDroid/platform_bionic/commit/c946249973b8b95f8f027e895325a89957c5c537 + https://github.com/TrebleDroid/device_phh_treble/commit/ecd7c745e32b0be6de4a74347537800d38f8015c

**Comment by JonnyVR1** [comment]
Nice one, guess we can call this closed
