### ISSUE TITLE
F

### ISSUE THREAD

**Issue by TimsFong** [TrebleDroid/treble_experimentations#84]

**Comment by phhusson** [comment]
Did previous one boot?

**Comment by TimsFong** [comment]
> Did previous one boot?

yes.14.0.0_r14 ci-20231125-td-arm64-ab-vanilla.img easy to boot.

**Comment by TimsFong** [comment]
[logs.txt](https://github.com/TrebleDroid/treble_experimentations/files/13622745/logs.txt)

**Comment by phhusson** [comment]
Why are you keeping basic information secret?

I would say your issue is with your custom vendor. I normally don't provide support for custom vendors, but let's try.
In addition to the normal trivial info, I'll need you to run `getprop persist.graphics.egl` and `getprop ro.hardware.egl` on 14.0.0_r14 ci-20231125-td-arm64-ab-vanilla.img

**Comment by TimsFong** [comment]
sorry. Since custom vendors are not supported, I don't want to say anything more. My device already has LineageOS official 17.1/18.1/19.1/20/21 available. Also, I don't know how to run these. Thank you so much.
![Screenshot_20231209-222104](https://github.com/TrebleDroid/treble_experimentations/assets/40086762/332cc054-9dfb-4552-a118-7ecbe70573ce)

**Comment by phhusson** [comment]
K, I don't understand why you want to keep basic info like your device name, or where you got your vendor from secret, but good

**Comment by phhusson** [comment]
Good news for you. I'm hitting the same issue on Blackview BV9800 Pro on official vendor.

**Comment by phhusson** [comment]
Fixed in https://github.com/TrebleDroid/platform_frameworks_native/commit/22753b80ed036ed392e25ce31df4eb95072abafa

**Comment by TimsFong** [comment]
yes.now is perfect。thanks a lot.
![Screenshot_20231221-030440](https://github.com/TrebleDroid/treble_experimentations/assets/40086762/8f21c6df-777c-40f2-bf4e-5e1b73ec167b)
