### ISSUE TITLE
Cannot send or receive SMS - SMSC set correctly

### ISSUE THREAD

**Issue by atlantix0815** [TrebleDroid/treble_experimentations#98]
### Current Behavior:
When I try to send a text messagge via any SMS app the SMS is not send. I also cannot receive any SMS I send to my number.
  
### Describe the bug
I am not able to send or receive any SMS although SMSC is set correctly.

### To Reproduce
1. Go to SMS app, click on '+', enter cotact's number and SMS text.
2. Click on '>' (send).
3. Wait a second.
4. See error "Not sent. Tap to try again." and "Can't send message with [provider], error 0"

### Expected behavior
The SMS should be sent. I should be able to receive SMS messages.

### Smartphone (please complete the following information):
 - Device: SM-S911B (Samsung S23, EU Snapdragon version)
 - Build Flavor: android_14.0.0_r21 ci-20240130
 - Version: ci-20240130 

### Additional context
I have attached a logfile I generated form the command "adb logcat -b radio". I tried to send the SMS right before the end of the log. Also note that when I use old vendor from Samsung (Android 13) I am able to send and receive SMS, but the system becomes laggy and I only have 3G data connection. Some people also reported similar problems on xda. See https://xdaforums.com/t/solved-sms-not-working-on-many-gsi-i-tried.4641394/, https://xdaforums.com/t/solved-gsi-related-can-not-receive-sms.4636173/ or https://xdaforums.com/t/how-to-fix-ril-sms-receiving-on-a23-5g.4654449/.
[radio.log](https://github.com/TrebleDroid/treble_experimentations/files/14312326/radio.log)

**Comment by atlantix0815** [comment]
Okay, I typed in the SMSC number again (which should not be necessary as it should has been set correctly), and tried to send a message. This time the message was sent as no error message appeared. BUT I still cannot receive any SMS. (I also tried to message myself). Log attached.
[radio.log](https://github.com/TrebleDroid/treble_experimentations/files/14313736/radio.log)

**Comment by atlantix0815** [comment]
Issue fixed with latest ci-20240226. SMS sending and receiving works as expected.

**Comment by tacstick** [comment]
Quick question, do sms messages work on android 15 ci-20241108? if so do they work on newer android 15 or 16 images?
